name: paysa
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get_storage: ^2.1.1
  http: ^1.0.0
  jwt_decoder: ^2.0.1
  custom_refresh_indicator: ^3.0.0
  url_launcher: ^6.2.4
  intl: ^0.19.0
  permission_handler: ^11.3.1
  image_picker: ^1.0.7
  logger: ^2.0.2+1
  cherry_toast: ^1.8.0
  iconsax: ^0.0.8
  get: ^4.6.6
  lottie: 
  salomon_bottom_bar: ^3.3.2
  grouped_list: ^6.0.0
  firebase_core: 
  firebase_auth: 
  google_sign_in: 
  cloud_firestore: 
  firebase_crashlytics: 
  firebase_analytics: 
  uuid: ^4.3.3
  pull_down_button: ^0.10.1 
  cached_network_image: ^3.3.1
  flex_color_scheme: ^7.3.1
  mrx_charts: ^0.1.3
  shimmer: ^3.0.0
  fl_chart: ^0.68.0
  encrypt: ^5.0.3
  firebase_messaging: ^15.0.4
  smooth_corner: ^1.1.0
  flashy_tab_bar2: ^0.0.10
  device_info_plus: ^10.1.2
  firebase_storage: 
  path_provider: any
  path: any
  zoom_tap_animation: ^1.1.0
  dashed_circular_progress_bar: ^0.0.6
  flutter_secure_storage: ^9.2.2
  home_widget: 
  davinci: ^2.5.1
  image_cropper: ^8.0.2
  google_generative_ai: ^0.4.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/expanses_category_icons/
    - assets/lottie/
    # - assets/icons/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic

    - family: Rubik
      fonts:
        - asset: assets/fonts/rubik/Rubik-light.ttf
          weight: 300
        - asset: assets/fonts/rubik/Rubik-lightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/rubik/Rubik-regular.ttf
        - asset: assets/fonts/rubik/Rubik-regularItalic.ttf
          style: italic
        - asset: assets/fonts/rubik/Rubik-medium.ttf
          weight: 500
        - asset: assets/fonts/rubik/Rubik-mediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/rubik/Rubik-semiBold.ttf
          weight: 600
        - asset: assets/fonts/rubik/Rubik-semiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/rubik/Rubik-bold.ttf
          weight: 700
        - asset: assets/fonts/rubik/Rubik-boldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/rubik/Rubik-extraBold.ttf
          weight: 800
        - asset: assets/fonts/rubik/Rubik-extraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/rubik/Rubik-black.ttf
          weight: 900
        - asset: assets/fonts/rubik/Rubik-blackItalic.ttf 
          weight: 900
          style: italic


      

 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
