// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR07N4zByvVBZt-oqC94WGmfB8jH4zL5k',
    appId: '1:224319668718:android:dd1a0c832861726c454eff',
    messagingSenderId: '224319668718',
    projectId: 'paysa-27149',
    storageBucket: 'paysa-27149.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX31QLbuNEeBYHw7egBDUsnd7m2KsBZk0',
    appId: '1:224319668718:ios:e8c19f6a12f75dfc454eff',
    messagingSenderId: '224319668718',
    projectId: 'paysa-27149',
    storageBucket: 'paysa-27149.appspot.com',
    androidClientId: '224319668718-0v2eo6jrnr9hsh5k3h6mhvb68q2iv3nl.apps.googleusercontent.com',
    iosClientId: '224319668718-tbp9ikeo642ejn0fg0kh3dm2d5bj4563.apps.googleusercontent.com',
    iosBundleId: 'com.example.paysa',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnzsQX8VbrqPLNOSlWSoUixCDtyrXyqbM',
    appId: '1:224319668718:web:fd5577c3ba675cb3454eff',
    messagingSenderId: '224319668718',
    projectId: 'paysa-27149',
    authDomain: 'paysa-27149.firebaseapp.com',
    storageBucket: 'paysa-27149.appspot.com',
    measurementId: 'G-502SLXH4RX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX31QLbuNEeBYHw7egBDUsnd7m2KsBZk0',
    appId: '1:224319668718:ios:e8c19f6a12f75dfc454eff',
    messagingSenderId: '224319668718',
    projectId: 'paysa-27149',
    storageBucket: 'paysa-27149.appspot.com',
    androidClientId: '224319668718-0v2eo6jrnr9hsh5k3h6mhvb68q2iv3nl.apps.googleusercontent.com',
    iosClientId: '224319668718-tbp9ikeo642ejn0fg0kh3dm2d5bj4563.apps.googleusercontent.com',
    iosBundleId: 'com.example.paysa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnzsQX8VbrqPLNOSlWSoUixCDtyrXyqbM',
    appId: '1:224319668718:web:6dda381be44101d5454eff',
    messagingSenderId: '224319668718',
    projectId: 'paysa-27149',
    authDomain: 'paysa-27149.firebaseapp.com',
    storageBucket: 'paysa-27149.appspot.com',
    measurementId: 'G-MFQG57BGYM',
  );

}