import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:paysa/Utils/constants/flags.dart';

class DashboardController extends GetxController {
  RxInt currentIndex = 0.obs;

  PageController pageController = PageController(initialPage: 0);

  Map<String, String> countryFlagWithCurrencyCode = {
    "AED": Flag.AE,
    "AFN": Flag.AF,
    "ALL": Flag.AL,
    "AMD": Flag.AM,
    "ANG": Flag.AW,
    "AOA": Flag.AO,
    "ARS": Flag.AR,
    "AUD": Flag.AU,
    "AWG": Flag.AW,
    "AZN": Flag.AZ,
    "BAM": Flag.BA,
    "BBD": Flag.BB,
    "BDT": Flag.BD,
    "BGN": Flag.BG,
    "BHD": Flag.BH,
    "BIF": Flag.BI,
    "BMD": Flag.BM,
    "BND": Flag.BN,
    "BOB": Flag.BO,
    "BRL": Flag.BR,
    "BSD": Flag.BS,
    "BTN": Flag.BT,
    "BWP": Flag.BW,
    "BYN": Flag.BY,
    "BZD": Flag.BZ,
    "CAD": Flag.CA,
    "CDF": Flag.CD,
    "CHF": Flag.CH,
    "CLP": Flag.CL,
    "CNY": Flag.CN,
    "COP": Flag.CO,
    "CRC": Flag.CR,
    "CUP": Flag.CU,
    "CVE": Flag.CV,
    "CZK": Flag.CZ,
    "DJF": Flag.DJ,
    "DKK": Flag.DK,
    "DOP": Flag.DO,
    "DZD": Flag.DZ,
    "EGP": Flag.EG,
    "ERN": Flag.ER,
    "ETB": Flag.ET,
    //  ÷ "EUR": Flag.EU,
    "FJD": Flag.FJ,
    "FKP": Flag.FK,
    "FOK": Flag.FO,
    "GBP": Flag.GB,
    "GEL": Flag.GE,
    "GGP": Flag.GG,
    "GHS": Flag.GH,
    "GIP": Flag.GI,
    "GMD": Flag.GM,
    "GNF": Flag.GN,
    "GTQ": Flag.GT,
    "GYD": Flag.GY,
    "HKD": Flag.HK,
    "HNL": Flag.HN,
    "HRK": Flag.HR,
    "HTG": Flag.HT,
    "HUF": Flag.HU,
    "IDR": Flag.ID,
    "ILS": Flag.IL,
    "IMP": Flag.IM,
    "INR": Flag.IN,
    "IQD": Flag.IQ,
    "IRR": Flag.IR,
    "ISK": Flag.IS,
    "JEP": Flag.JE,
    "JMD": Flag.JM,
    "JOD": Flag.JO,
    "JPY": Flag.JP,
    "KES": Flag.KE,
    "KGS": Flag.KG,
    "KHR": Flag.KH,
    "KID": Flag.KI,
    "KMF": Flag.KM,
    "KRW": Flag.KR,
    "KWD": Flag.KW,
    "KYD": Flag.KY,
    "KZT": Flag.KZ,
    "LAK": Flag.LA,
    "LBP": Flag.LB,
    "LKR": Flag.LK,
    "LRD": Flag.LR,
    "LSL": Flag.LS,
    "LYD": Flag.LY,
    "MAD": Flag.MA,
    "MDL": Flag.MD,
    "MGA": Flag.MG,
    "MKD": Flag.MK,
    "MMK": Flag.MM,
    "MNT": Flag.MN,
    "MOP": Flag.MO,
    "MRU": Flag.MR,
    "MUR": Flag.MU,
    "MVR": Flag.MV,
    "MWK": Flag.MW,
    "MXN": Flag.MX,
    "MYR": Flag.MY,
    "MZN": Flag.MZ,
    "NAD": Flag.NA,
    "NGN": Flag.NG,
    "NIO": Flag.NI,
    "NOK": Flag.NO,
    "NPR": Flag.NP,
    "NZD": Flag.NZ,
    "OMR": Flag.OM,
    "PAB": Flag.PA,
    "PEN": Flag.PE,
    "PGK": Flag.PG,
    "PHP": Flag.PH,
    "PKR": Flag.PK,
    "PLN": Flag.PL,
    "PYG": Flag.PY,
    "QAR": Flag.QA,
    "RON": Flag.RO,
    "RSD": Flag.RS,
    "RUB": Flag.RU,
    "RWF": Flag.RW,
    "SAR": Flag.SA,
    "SBD": Flag.SB,
    "SCR": Flag.SC,
    "SDG": Flag.SD,
    "SEK": Flag.SE,
    "SGD": Flag.SG,
    "SHP": Flag.SH,
    "SLL": Flag.SL,
    "SOS": Flag.SO,
    "SRD": Flag.SR,
    "SSP": Flag.SS,
    "STN": Flag.ST,
    "SYP": Flag.SY,
    "SZL": Flag.SZ,
    "THB": Flag.TH,
    "TJS": Flag.TJ,
    "TMT": Flag.TM,
    "TND": Flag.TN,
    "TOP": Flag.TO,
    "TRY": Flag.TR,
    "TTD": Flag.TT,
    "TVD": Flag.TV,
    "TWD": Flag.TW,
    "TZS": Flag.TZ,
    "UAH": Flag.UA,
    "UGX": Flag.UG,
    "USD": Flag.US,
    "UYU": Flag.UY,
    "UZS": Flag.UZ,
    "VES": Flag.VE,
    "VND": Flag.VN,
    "VUV": Flag.VU,
    "WST": Flag.WS,
    "XAF": Flag.CM,
    "XCD": Flag.LC,
    "XOF": Flag.BJ,
    "XPF": Flag.PF,
    "YER": Flag.YE,
    "ZAR": Flag.ZA,
    "ZMW": Flag.ZM,
  };

  void changePage(int index) {
    currentIndex.value = index;
    pageController.animateToPage(index,
        duration: const Duration(milliseconds: 400), curve: Curves.easeInOut);
  }

  void nextPage() {
    currentIndex.value++;
    pageController.animateToPage(currentIndex.value,
        duration: const Duration(milliseconds: 400), curve: Curves.easeInOut);
  }

  void previousPage() {
    currentIndex.value--;
    pageController.animateToPage(currentIndex.value,
        duration: const Duration(milliseconds: 400), curve: Curves.easeInOut);
  }
}
